"""
MelodyForge AI backend API.

Maps directly onto the app's screens:
  Home / Generate screen  -> POST /generate
  Training (offline/admin)-> POST /train
  Library screen           -> GET /tracks, GET /tracks/{id}/download
  Genre chips               -> GET /genres

Run locally with:
    uvicorn app.main:app --reload --port 8000
"""
import os
import time
import uuid
from typing import Literal

from fastapi import BackgroundTasks, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from . import config
from .demo_generator import generate_demo_sequence
from .midi_utils import tokens_to_midi
from .model import generate_sequence, train

app = FastAPI(title="MelodyForge AI API", version="1.0.0")

# Allow the Framer/mobile app's domain to call this API directly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten to your app's actual domain(s) in production
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory track registry for demo purposes; swap for a real DB (Postgres, etc.) in production.
TRACKS: dict[str, dict] = {}


# ---------- Schemas ----------

class GenerateRequest(BaseModel):
    genre: Literal["classical", "jazz", "pop", "lofi", "ambient"]
    mood: float = Field(0.5, ge=0.0, le=1.0, description="0 = calm, 1 = energetic")
    tempo_bpm: int = Field(120, ge=40, le=220)
    duration_notes: int = Field(200, ge=20, le=1000)


class TrainRequest(BaseModel):
    genre: Literal["classical", "jazz", "pop", "lofi", "ambient"]


class TrackOut(BaseModel):
    id: str
    title: str
    genre: str
    created_at: float
    download_url: str
    demo: bool = False  # True when generated by the rule-based fallback (no trained model yet)


# ---------- Endpoints ----------

@app.get("/genres")
def list_genres():
    """Populates the genre chips / dropdown on the Home & Generate screens."""
    return {"genres": config.GENRES}


@app.post("/train")
def train_model(req: TrainRequest, background_tasks: BackgroundTasks):
    """
    Kicks off Steps 1-4 (collect -> preprocess -> build -> train) for a genre.
    Training is slow, so it runs in the background; poll /tracks or a
    separate /train/status/{genre} endpoint (add a job table for that
    in production) to check progress.
    """
    background_tasks.add_task(train, req.genre)
    return {"status": "training_started", "genre": req.genre}


@app.post("/generate", response_model=TrackOut)
def generate_track(req: GenerateRequest):
    """
    Step 5: generate a new note sequence and convert it to MIDI.
    Powers the "Generate" button on the mobile app.

    Tries the trained LSTM model first (see model.py / preprocessing.py for
    the full collect -> preprocess -> train pipeline). If no model has been
    trained yet for this genre (no MIDI dataset uploaded / training not run),
    falls back to a rule-based demo generator so the app still works
    end-to-end. The response's `demo` field tells the frontend which one
    produced the track.
    """
    is_demo = False
    try:
        tokens = generate_sequence(
            genre=req.genre, length=req.duration_notes, mood=req.mood
        )
    except FileNotFoundError:
        tokens = generate_demo_sequence(
            genre=req.genre, length=req.duration_notes, mood=req.mood
        )
        is_demo = True

    midi_path = tokens_to_midi(tokens, bpm=req.tempo_bpm)

    track_id = uuid.uuid4().hex
    track = {
        "id": track_id,
        "title": f"{req.genre.title()} Piece #{len(TRACKS) + 1}" + (" (Demo)" if is_demo else ""),
        "genre": req.genre,
        "created_at": time.time(),
        "file_path": midi_path,
        "download_url": f"/tracks/{track_id}/download",
        "demo": is_demo,
    }
    TRACKS[track_id] = track
    return track


@app.get("/tracks", response_model=list[TrackOut])
def list_tracks(genre: str | None = None):
    """Powers the Library screen, with optional genre filter."""
    tracks = list(TRACKS.values())
    if genre:
        tracks = [t for t in tracks if t["genre"] == genre]
    tracks.sort(key=lambda t: t["created_at"], reverse=True)
    return tracks


@app.get("/tracks/{track_id}/download")
def download_track(track_id: str):
    """Serves the actual .mid file for playback/download in the app."""
    track = TRACKS.get(track_id)
    if not track or not os.path.exists(track["file_path"]):
        raise HTTPException(status_code=404, detail="Track not found")
    return FileResponse(
        track["file_path"],
        media_type="audio/midi",
        filename=f"{track['title']}.mid",
    )
